"""Add PlayedCard.

Revision ID: 4b18eb9c46c
Revises: 27fc35d77c0
Create Date: 2015-05-03 19:35:03.175149

"""

# revision identifiers, used by Alembic.
revision = '4b18eb9c46c'
down_revision = '27fc35d77c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('played_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], name=op.f('fk_played_card_card_id_card')),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_played_card_game_id_game')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_played_card'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('played_card')
    ### end Alembic commands ###
