"""Initial revision.

Revision ID: 27fc35d77c0
Revises: None
Create Date: 2015-05-02 12:30:56.755041

"""

# revision identifiers, used by Alembic.
revision = '27fc35d77c0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('good',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_good')),
    sa.UniqueConstraint('name', name=op.f('uq_good_name'))
    )
    op.create_table('world',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_world')),
    sa.UniqueConstraint('name', name=op.f('uq_world_name'))
    )
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('event', sa.Text(), nullable=True),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['world.id'], name=op.f('fk_card_world_id_world')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card'))
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['world.id'], name=op.f('fk_city_world_id_world')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_city'))
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['world.id'], name=op.f('fk_game_world_id_world')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game'))
    )
    op.create_table('city_produces',
    sa.Column('good_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f('fk_city_produces_city_id_city')),
    sa.ForeignKeyConstraint(['good_id'], ['good.id'], name=op.f('fk_city_produces_good_id_good'))
    )
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('good_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f('fk_contract_city_id_city')),
    sa.ForeignKeyConstraint(['good_id'], ['good.id'], name=op.f('fk_contract_good_id_good')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contract'))
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('money', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_player_game_id_game')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player'))
    )
    op.create_table('card_contract',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], name=op.f('fk_card_contract_card_id_card')),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], name=op.f('fk_card_contract_contract_id_contract'))
    )
    op.create_table('player_card',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], name=op.f('fk_player_card_card_id_card')),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('fk_player_card_player_id_player'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_card')
    op.drop_table('card_contract')
    op.drop_table('player')
    op.drop_table('contract')
    op.drop_table('city_produces')
    op.drop_table('game')
    op.drop_table('city')
    op.drop_table('card')
    op.drop_table('world')
    op.drop_table('good')
    ### end Alembic commands ###
